### ISSUE TITLE
How many secrets do we currently have in this repo ?

### ISSUE THREAD

**Issue by kimmanni** [octodemo/custom-pattern-secrets#73]
Hello,

I'm testing out gitleaks and I see that it detected 17 secrets in this repo , but how do I find how many patterns are listed out in this?

**Comment by aegilops** [comment]
Most of the `patterns.yml` files have an `expected` key that relates to detections in files in the same directory as the YAML file. The start and end offset in bytes of the secret are given along with the filename.

There are also files in the `__snapshots__` directory of each pattern that document the expected secret detections. That format isn't documented, but should be easy to figure out.

Both are used in regression testing of the patterns.
