### ISSUE TITLE
IBAN

### ISSUE THREAD

**Issue by GeekMasher** [octodemo/custom-pattern-secrets#8]
### Name / Description

IBAN IDs/Numbers

### Sample Snippets

**True Positives**

```
DE89 3704 0044 0532 0130 00
AT61 1904 3002 3457 3201
GB82-WEST-1234-5698-7654-32
NL20INGB0001234567
```

**False Positives**

```
0089 3704 0044 0532 0130 00
```

### [optional] Propose Solution

Take a look at: #7 

```regex
[A-Z]{2}[0-9]{2}( |-)?([0-9A-Z]{4})?(?:( |-)?[0-9]){14,20}
```

**Comment by aegilops** [comment]
Shipped this in https://github.com/advanced-security/secret-scanning-custom-patterns/pull/7
